# Generated by Django 4.1.3 on 2022-11-18 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=50, verbose_name='Doctor Name')),
                ('dmobile', models.CharField(max_length=12, verbose_name='Doctor Mobile No.')),
                ('dqualification', models.CharField(max_length=50, verbose_name='Doctor Qualification')),
                ('dspecialization', models.CharField(max_length=50, verbose_name='Doctor Specialization')),
                ('yoe', models.CharField(max_length=50, verbose_name='Doctor Experience')),
            ],
        ),
        migrations.CreateModel(
            name='userRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=12, verbose_name='Patient Mobile No.')),
                ('pat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=50, verbose_name="Doctor's days")),
                ('time', models.CharField(max_length=50, verbose_name='Timing')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='accounts.doctor', verbose_name='Doctor')),
            ],
        ),
    ]
