# Generated by Django 4.1.3 on 2022-11-18 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('apid', models.AutoField(primary_key=True, serialize=False)),
                ('apmade', models.DateField(auto_now_add=True, verbose_name='Appointment Making Time')),
                ('apdate', models.DateField(verbose_name='Appontment Date')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor', verbose_name='Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
            ],
        ),
    ]
